package com.nekomu.xerocore.common.machine.multiblock.steam;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.common.data.GTRecipeTypes;
import com.nekomu.xerocore.client.renderer.machine.XeroDynamicRendererHelpers;

import static com.gregtechceu.gtceu.api.pattern.Predicates.abilities;
import static com.gregtechceu.gtceu.api.pattern.Predicates.blocks;
import static com.gregtechceu.gtceu.common.data.GTBlocks.*;
import static com.gregtechceu.gtceu.common.data.GTRecipeModifiers.BATCH_MODE;
import static com.gregtechceu.gtceu.common.data.GTRecipeModifiers.OC_NON_PERFECT_SUBTICK;
import static com.gregtechceu.gtceu.common.data.models.GTMachineModels.createWorkableCasingMachineModel;
import static com.nekomu.xerocore.api.registries.XeroRegistries.REGISTRATE;

public class testmachine {
    public static final MachineDefinition TEST_MACHINE = REGISTRATE.multiblock("test_machine", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(GTRecipeTypes.ALLOY_SMELTER_RECIPES)
            .recipeModifiers(OC_NON_PERFECT_SUBTICK, BATCH_MODE)
            .appearanceBlock(CASING_BRONZE_BRICKS)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("                                         AAAAAAAAAAAAAAA                                         ","                                         BBBBBBBBBBBBBBB                                         ","                                         BBBBBBBBBBBBBBB                                         ","                                         AAAAAAAAAAAAAAA                                         ")
                    .aisle("                                    AAAAACCCCCCCCCCCCCCCAAAAA                                    ","                                    BBBBB               BBBBB                                    ","                                    BBBBB               BBBBB                                    ","                                    AAAAACCCCCCCCCCCCCCCAAAAA                                    ")
                    .aisle("                                 AAACCCCCCCCCCCCCCCCCCCCCCCCCAAA                                 ","                                 BBB                         BBB                                 ","                                 BBB                         BBB                                 ","                                 AAACCCCCCCCCCCCCCCCCCCCCCCCCAAA                                 ")
                    .aisle("                               AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                               ","                               BB                               BB                               ","                               BB                               BB                               ","                               AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                               ")
                    .aisle("                             AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                             ","                             BB                                   BB                             ","                             BB                                   BB                             ","                             AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                             ")
                    .aisle("                           AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                           ","                           BB                                       BB                           ","                           BB                                       BB                           ","                           AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                           ")
                    .aisle("                         AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                         ","                         BB                                           BB                         ","                         BB                                           BB                         ","                         AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                         ")
                    .aisle("                       AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                       ","                       BB                                               BB                       ","                       BB                                               BB                       ","                       AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                       ")
                    .aisle("                      ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                      ","                      B                                                   B                      ","                      B                                                   B                      ","                      ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                      ")
                    .aisle("                    AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                    ","                    BB                                                     BB                    ","                    BB                                                     BB                    ","                    AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                    ")
                    .aisle("                   ACCCCCCCCCCCCCCCCCCCCCCAAAAAAAAAAAAACCCCCCCCCCCCCCCCCCCCCCA                   ","                   B                      BBBBBBBBBBBBB                      B                   ","                   B                      BBBBBBBBBBBBB                      B                   ","                   ACCCCCCCCCCCCCCCCCCCCCCAAAAAAAAAAAAACCCCCCCCCCCCCCCCCCCCCCA                   ")
                    .aisle("                  ACCCCCCCCCCCCCCCCCCAAAAA             AAAAACCCCCCCCCCCCCCCCCCA                  ","                  B                  BBBBB             BBBBB                  B                  ","                  B                  BBBBB             BBBBB                  B                  ","                  ACCCCCCCCCCCCCCCCCCAAAAA             AAAAACCCCCCCCCCCCCCCCCCA                  ")
                    .aisle("                 ACCCCCCCCCCCCCCCCAAA                       AAACCCCCCCCCCCCCCCCA                 ","                 B                BBB                       BBB                B                 ","                 B                BBB                       BBB                B                 ","                 ACCCCCCCCCCCCCCCCAAA                       AAACCCCCCCCCCCCCCCCA                 ")
                    .aisle("                ACCCCCCCCCCCCCCCAA                             AACCCCCCCCCCCCCCCA                ","                B               BB                             BB               B                ","                B               BB                             BB               B                ","                ACCCCCCCCCCCCCCCAA                             AACCCCCCCCCCCCCCCA                ")
                    .aisle("               ACCCCCCCCCCCCCCAA                                 AACCCCCCCCCCCCCCA               ","               B              BB                                 BB              B               ","               B              BB                                 BB              B               ","               ACCCCCCCCCCCCCCAA                                 AACCCCCCCCCCCCCCA               ")
                    .aisle("              ACCCCCCCCCCCCCCA                                     ACCCCCCCCCCCCCCA              ","              B              B                                     B              B              ","              B              B                                     B              B              ","              ACCCCCCCCCCCCCCA                                     ACCCCCCCCCCCCCCA              ")
                    .aisle("             ACCCCCCCCCCCCCAA                                       AACCCCCCCCCCCCCA             ","             B             BB                                       BB             B             ","             B             BB                                       BB             B             ","             ACCCCCCCCCCCCCAA                                       AACCCCCCCCCCCCCA             ")
                    .aisle("            ACCCCCCCCCCCCAA                                           AACCCCCCCCCCCCA            ","            B            BB                                           BB            B            ","            B            BB                                           BB            B            ","            ACCCCCCCCCCCCAA                                           AACCCCCCCCCCCCA            ")
                    .aisle("           ACCCCCCCCCCCCA                                               ACCCCCCCCCCCCA           ","           B            B                                               B            B           ","           B            B                                               B            B           ","           ACCCCCCCCCCCCA                                               ACCCCCCCCCCCCA           ")
                    .aisle("          ACCCCCCCCCCCCA                                                 ACCCCCCCCCCCCA          ","          B            B                                                 B            B          ","          B            B                                                 B            B          ","          ACCCCCCCCCCCCA                                                 ACCCCCCCCCCCCA          ")
                    .aisle("         ACCCCCCCCCCCCA                                                   ACCCCCCCCCCCCA         ","         B            B                                                   B            B         ","         B            B                                                   B            B         ","         ACCCCCCCCCCCCA                                                   ACCCCCCCCCCCCA         ")
                    .aisle("         ACCCCCCCCCCCA                                                     ACCCCCCCCCCCA         ","         B           B                                                     B           B         ","         B           B                                                     B           B         ","         ACCCCCCCCCCCA                                                     ACCCCCCCCCCCA         ")
                    .aisle("        ACCCCCCCCCCCA                                                       ACCCCCCCCCCCA        ","        B           B                                                       B           B        ","        B           B                                                       B           B        ","        ACCCCCCCCCCCA                                                       ACCCCCCCCCCCA        ")
                    .aisle("       ACCCCCCCCCCCA                                                         ACCCCCCCCCCCA       ","       B           B                                                         B           B       ","       B           B                                                         B           B       ","       ACCCCCCCCCCCA                                                         ACCCCCCCCCCCA       ")
                    .aisle("       ACCCCCCCCCCA                       AAAAAAAAAAAAA                       ACCCCCCCCCCA       ","       B          B                       BBBBBBBBBBBBB                       B          B       ","       B          B                       BBBBBBBBBBBBB                       B          B       ","       ACCCCCCCCCCA                       AAAAAAAAAAAAA                       ACCCCCCCCCCA       ")
                    .aisle("      ACCCCCCCCCCA                     AAACCCCCCCCCCCCCAAA                     ACCCCCCCCCCA      ","      B          B                     BBB             BBB                     B          B      ","      B          B                     BBB             BBB                     B          B      ","      ACCCCCCCCCCA                     AAACCCCCCCCCCCCCAAA                     ACCCCCCCCCCA      ")
                    .aisle("      ACCCCCCCCCCA                   AACCCCCCCCCCCCCCCCCCCAA                   ACCCCCCCCCCA      ","      B          B                   BB                   BB                   B          B      ","      B          B                   BB                   BB                   B          B      ","      ACCCCCCCCCCA                   AACCCCCCCCCCCCCCCCCCCAA                   ACCCCCCCCCCA      ")
                    .aisle("     ACCCCCCCCCCA                  AACCCCCCCCCCCCCCCCCCCCCCCAA                  ACCCCCCCCCCA     ","     B          B                  BB                       BB                  B          B     ","     B          B                  BB                       BB                  B          B     ","     ACCCCCCCCCCA                  AACCCCCCCCCCCCCCCCCCCCCCCAA                  ACCCCCCCCCCA     ")
                    .aisle("     ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA     ","     B          B                 B                           B                 B          B     ","     B          B                 B                           B                 B          B     ","     ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA     ")
                    .aisle("    ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA    ","    B          B                 B                             B                 B          B    ","    B          B                 B                             B                 B          B    ","    ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA    ")
                    .aisle("    ACCCCCCCCCA                 ACCCCCCCCCCCAAAAAAAAACCCCCCCCCCCA                 ACCCCCCCCCA    ","    B         B                 B           BBBBBBBBB           B                 B         B    ","    B         B                 B           BBBBBBBBB           B                 B         B    ","    ACCCCCCCCCA                 ACCCCCCCCCCCAAAAAAAAACCCCCCCCCCCA                 ACCCCCCCCCA    ")
                    .aisle("   ACCCCCCCCCCA                ACCCCCCCCCAAA         AAACCCCCCCCCA                ACCCCCCCCCCA   ","   B          B                B         BBB         BBB         B                B          B   ","   B          B                B         BBB         BBB         B                B          B   ","   ACCCCCCCCCCA                ACCCCCCCCCAAA         AAACCCCCCCCCA                ACCCCCCCCCCA   ")
                    .aisle("   ACCCCCCCCCA                ACCCCCCCCAA               AACCCCCCCCA                ACCCCCCCCCA   ","   B         B                B        BB               BB        B                B         B   ","   B         B                B        BB               BB        B                B         B   ","   ACCCCCCCCCA                ACCCCCCCCAA               AACCCCCCCCA                ACCCCCCCCCA   ")
                    .aisle("  ACCCCCCCCCCA               ACCCCCCCAA                   AACCCCCCCA               ACCCCCCCCCCA  ","  B          B               B       BB                   BB       B               B          B  ","  B          B               B       BB                   BB       B               B          B  ","  ACCCCCCCCCCA               ACCCCCCCAA                   AACCCCCCCA               ACCCCCCCCCCA  ")
                    .aisle("  ACCCCCCCCCA               ACCCCCCCA                       ACCCCCCCA               ACCCCCCCCCA  ","  B         B               B       B                       B       B               B         B  ","  B         B               B       B                       B       B               B         B  ","  ACCCCCCCCCA               ACCCCCCCA                       ACCCCCCCA               ACCCCCCCCCA  ")
                    .aisle("  ACCCCCCCCCA              ACCCCCCCA                         ACCCCCCCA              ACCCCCCCCCA  ","  B         B              B       B                         B       B              B         B  ","  B         B              B       B                         B       B              B         B  ","  ACCCCCCCCCA              ACCCCCCCA                         ACCCCCCCA              ACCCCCCCCCA  ")
                    .aisle(" ACCCCCCCCCCA              ACCCCCCA                           ACCCCCCA              ACCCCCCCCCCA "," B          B              B      B                           B      B              B          B "," B          B              B      B                           B      B              B          B "," ACCCCCCCCCCA              ACCCCCCA                           ACCCCCCA              ACCCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA "," B         B              B      B                             B      B              B         B "," B         B              B      B                             B      B              B         B "," ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA "," B         B              B      B                             B      B              B         B "," B         B              B      B                             B      B              B         B "," ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA "," B         B             B      B                               B      B             B         B "," B         B             B      B                               B      B             B         B "," ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA "," B         B             B      B                               B      B             B         B "," B         B             B      B                               B      B             B         B "," ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA ")
                    .aisle("ACCCCCCCCCCA             ACCCCCA                                 ACCCCCA             ACCCCCCCCCCA","B          B             B     B                                 B     B             B          B","B          B             B     B                                 B     B             B          B","ACCCCCCCCCCA             ACCCCCA                                 ACCCCCA             ACCCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA","B         B             B      B                                 B      B             B         B","B         B             B      B                                 B      B             B         B","ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA","B         B             B      B                                 B      B             B         B","B         B             B      B                                 B      B             B         B","ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA","B         B             B     B                                   B     B             B         B","B         B             B     B                                   B     B             B         B","ACCCCCCCCCA             ACCCCCA                                   ACCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA","B         B             B      B                                 B      B             B         B","B         B             B      B                                 B      B             B         B","ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA","B         B             B      B                                 B      B             B         B","B         B             B      B                                 B      B             B         B","ACCCCCCCCCA             ACCCCCCA                                 ACCCCCCA             ACCCCCCCCCA")
                    .aisle("ACCCCCCCCCCA             ACCCCCA                                 ACCCCCA             ACCCCCCCCCCA","B          B             B     B                                 B     B             B          B","B          B             B     B                                 B     B             B          B","ACCCCCCCCCCA             ACCCCCA                                 ACCCCCA             ACCCCCCCCCCA")
                    .aisle(" ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA "," B         B             B      B                               B      B             B         B "," B         B             B      B                               B      B             B         B "," ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA "," B         B             B      B                               B      B             B         B "," B         B             B      B                               B      B             B         B "," ACCCCCCCCCA             ACCCCCCA                               ACCCCCCA             ACCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA "," B         B              B      B                             B      B              B         B "," B         B              B      B                             B      B              B         B "," ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA "," B         B              B      B                             B      B              B         B "," B         B              B      B                             B      B              B         B "," ACCCCCCCCCA              ACCCCCCA                             ACCCCCCA              ACCCCCCCCCA ")
                    .aisle(" ACCCCCCCCCCA              ACCCCCCA                           ACCCCCCA              ACCCCCCCCCCA "," B          B              B      B                           B      B              B          B "," B          B              B      B                           B      B              B          B "," ACCCCCCCCCCA              ACCCCCCA                           ACCCCCCA              ACCCCCCCCCCA ")
                    .aisle("  ACCCCCCCCCA              ACCCCCCCA                         ACCCCCCCA              ACCCCCCCCCA  ","  B         B              B       B                         B       B              B         B  ","  B         B              B       B                         B       B              B         B  ","  ACCCCCCCCCA              ACCCCCCCA                         ACCCCCCCA              ACCCCCCCCCA  ")
                    .aisle("  ACCCCCCCCCA               ACCCCCCCA                       ACCCCCCCA               ACCCCCCCCCA  ","  B         B               B       B                       B       B               B         B  ","  B         B               B       B                       B       B               B         B  ","  ACCCCCCCCCA               ACCCCCCCA                       ACCCCCCCA               ACCCCCCCCCA  ")
                    .aisle("  ACCCCCCCCCCA               ACCCCCCCAA                   AACCCCCCCA               ACCCCCCCCCCA  ","  B          B               B       BB                   BB       B               B          B  ","  B          B               B       BB                   BB       B               B          B  ","  ACCCCCCCCCCA               ACCCCCCCAA                   AACCCCCCCA               ACCCCCCCCCCA  ")
                    .aisle("   ACCCCCCCCCA                ACCCCCCCCAA               AACCCCCCCCA                ACCCCCCCCCA   ","   B         B                B        BB               BB        B                B         B   ","   B         B                B        BB               BB        B                B         B   ","   ACCCCCCCCCA                ACCCCCCCCAA               AACCCCCCCCA                ACCCCCCCCCA   ")
                    .aisle("   ACCCCCCCCCCA                ACCCCCCCCCAAA         AAACCCCCCCCCA                ACCCCCCCCCCA   ","   B          B                B         BBB         BBB         B                B          B   ","   B          B                B         BBB         BBB         B                B          B   ","   ACCCCCCCCCCA                ACCCCCCCCCAAA         AAACCCCCCCCCA                ACCCCCCCCCCA   ")
                    .aisle("    ACCCCCCCCCA                 ACCCCCCCCCCCAAAAAAAAACCCCCCCCCCCA                 ACCCCCCCCCA    ","    B         B                 B           BBBBBBBBB           B                 B         B    ","    B         B                 B           BBBBBBBBB           B                 B         B    ","    ACCCCCCCCCA                 ACCCCCCCCCCCAAAAAAAAACCCCCCCCCCCA                 ACCCCCCCCCA    ")
                    .aisle("    ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA    ","    B          B                 B                             B                 B          B    ","    B          B                 B                             B                 B          B    ","    ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA    ")
                    .aisle("     ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA     ","     B          B                 B                           B                 B          B     ","     B          B                 B                           B                 B          B     ","     ACCCCCCCCCCA                 ACCCCCCCCCCCCCCCCCCCCCCCCCCCA                 ACCCCCCCCCCA     ")
                    .aisle("     ACCCCCCCCCCA                  AACCCCCCCCCCCCCCCCCCCCCCCAA                  ACCCCCCCCCCA     ","     B          B                  BB                       BB                  B          B     ","     B          B                  BB                       BB                  B          B     ","     ACCCCCCCCCCA                  AACCCCCCCCCCCCCCCCCCCCCCCAA                  ACCCCCCCCCCA     ")
                    .aisle("      ACCCCCCCCCCA                   AACCCCCCCCCCCCCCCCCCCAA                   ACCCCCCCCCCA      ","      B          B                   BB                   BB                   B          B      ","      B          B                   BB                   BB                   B          B      ","      ACCCCCCCCCCA                   AACCCCCCCCCCCCCCCCCCCAA                   ACCCCCCCCCCA      ")
                    .aisle("      ACCCCCCCCCCA                     AAACCCCCCCCCCCCCAAA                     ACCCCCCCCCCA      ","      B          B                     BBB             BBB                     B          B      ","      B          B                     BBB             BBB                     B          B      ","      ACCCCCCCCCCA                     AAACCCCCCCCCCCCCAAA                     ACCCCCCCCCCA      ")
                    .aisle("       ACCCCCCCCCCA                       AAAAAAAAAAAAA                       ACCCCCCCCCCA       ","       B          B                       BBBBBBBBBBBBB                       B          B       ","       B          B                       BBBBBBBBBBBBB                       B          B       ","       ACCCCCCCCCCA                       AAAAAAAAAAAAA                       ACCCCCCCCCCA       ")
                    .aisle("       ACCCCCCCCCCCA                                                         ACCCCCCCCCCCA       ","       B           B                                                         B           B       ","       B           B                                                         B           B       ","       ACCCCCCCCCCCA                                                         ACCCCCCCCCCCA       ")
                    .aisle("        ACCCCCCCCCCCA                                                       ACCCCCCCCCCCA        ","        B           B                                                       B           B        ","        B           B                                                       B           B        ","        ACCCCCCCCCCCA                                                       ACCCCCCCCCCCA        ")
                    .aisle("         ACCCCCCCCCCCA                                                     ACCCCCCCCCCCA         ","         B           B                                                     B           B         ","         B           B                                                     B           B         ","         ACCCCCCCCCCCA                                                     ACCCCCCCCCCCA         ")
                    .aisle("         ACCCCCCCCCCCCA                                                   ACCCCCCCCCCCCA         ","         B            B                                                   B            B         ","         B            B                                                   B            B         ","         ACCCCCCCCCCCCA                                                   ACCCCCCCCCCCCA         ")
                    .aisle("          ACCCCCCCCCCCCA                                                 ACCCCCCCCCCCCA          ","          B            B                                                 B            B          ","          B            B                                                 B            B          ","          ACCCCCCCCCCCCA                                                 ACCCCCCCCCCCCA          ")
                    .aisle("           ACCCCCCCCCCCCA                                               ACCCCCCCCCCCCA           ","           B            B                                               B            B           ","           B            B                                               B            B           ","           ACCCCCCCCCCCCA                                               ACCCCCCCCCCCCA           ")
                    .aisle("            ACCCCCCCCCCCCAA                                           AACCCCCCCCCCCCA            ","            B            BB                                           BB            B            ","            B            BB                                           BB            B            ","            ACCCCCCCCCCCCAA                                           AACCCCCCCCCCCCA            ")
                    .aisle("             ACCCCCCCCCCCCCAA                                       AACCCCCCCCCCCCCA             ","             B             BB                                       BB             B             ","             B             BB                                       BB             B             ","             ACCCCCCCCCCCCCAA                                       AACCCCCCCCCCCCCA             ")
                    .aisle("              ACCCCCCCCCCCCCCA                                     ACCCCCCCCCCCCCCA              ","              B              B                                     B              B              ","              B              B                                     B              B              ","              ACCCCCCCCCCCCCCA                                     ACCCCCCCCCCCCCCA              ")
                    .aisle("               ACCCCCCCCCCCCCCAA                                 AACCCCCCCCCCCCCCA               ","               B              BB                                 BB              B               ","               B              BB                                 BB              B               ","               ACCCCCCCCCCCCCCAA                                 AACCCCCCCCCCCCCCA               ")
                    .aisle("                ACCCCCCCCCCCCCCCAA                             AACCCCCCCCCCCCCCCA                ","                B               BB                             BB               B                ","                B               BB                             BB               B                ","                ACCCCCCCCCCCCCCCAA                             AACCCCCCCCCCCCCCCA                ")
                    .aisle("                 ACCCCCCCCCCCCCCCCAAA                       AAACCCCCCCCCCCCCCCCA                 ","                 B                BBB                       BBB                B                 ","                 B                BBB                       BBB                B                 ","                 ACCCCCCCCCCCCCCCCAAA                       AAACCCCCCCCCCCCCCCCA                 ")
                    .aisle("                  ACCCCCCCCCCCCCCCCCCAAAAA             AAAAACCCCCCCCCCCCCCCCCCA                  ","                  B                  BBBBB             BBBBB                  B                  ","                  B                  BBBBB             BBBBB                  B                  ","                  ACCCCCCCCCCCCCCCCCCAAAAA             AAAAACCCCCCCCCCCCCCCCCCA                  ")
                    .aisle("                   ACCCCCCCCCCCCCCCCCCCCCCAAAAAAAAAAAAACCCCCCCCCCCCCCCCCCCCCCA                   ","                   B                      BBBBBBBBBBBBB                      B                   ","                   B                      BBBBBBBBBBBBB                      B                   ","                   ACCCCCCCCCCCCCCCCCCCCCCAAAAAAAAAAAAACCCCCCCCCCCCCCCCCCCCCCA                   ")
                    .aisle("                    AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                    ","                    BB                                                     BB                    ","                    BB                                                     BB                    ","                    AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                    ")
                    .aisle("                      ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                      ","                      B                                                   B                      ","                      B                                                   B                      ","                      ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA                      ")
                    .aisle("                       AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                       ","                       BB                                               BB                       ","                       BB                                               BB                       ","                       AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                       ")
                    .aisle("                         AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                         ","                         BB                                           BB                         ","                         BB                                           BB                         ","                         AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                         ")
                    .aisle("                           AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                           ","                           BB                                       BB                           ","                           BB                                       BB                           ","                           AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                           ")
                    .aisle("                             AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                             ","                             BB                                   BB                             ","                             BB                                   BB                             ","                             AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                             ")
                    .aisle("                               AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                               ","                               BB                               BB                               ","                               BB                               BB                               ","                               AACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA                               ")
                    .aisle("                                 AAACCCCCCCCCCCCCCCCCCCCCCCCCAAA                                 ","                                 BBB                         BBB                                 ","                                 BBB                         BBB                                 ","                                 AAACCCCCCCCCCCCCCCCCCCCCCCCCAAA                                 ")
                    .aisle("                                    AAAAACCCCCCCCCCCCCCCAAAAA                                    ","                                    BBBBB               BBBBB                                    ","                                    BBBBB               BBBBB                                    ","                                    AAAAACCCCCCCCCCCCCCCAAAAA                                    ")
                    .aisle("                                         AAAAAAAAAAAAAAA                                         ","                                         BBBBBBBBBBBBBBB                                         ","                                         BBBBBBB@BBBBBBB                                         ","                                         AAAAAAAAAAAAAAA                                         ")
                    .where('@', Predicates.controller(blocks(definition.getBlock())))
                    .where(' ', Predicates.any())
                    .where('A', blocks(CASING_PTFE_INERT.get()))
                    .where('C', blocks(MACHINE_CASING_MAX.get()))
                    .where('B', blocks(CASING_ALUMINIUM_FROSTPROOF.get())
                            .or(abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(abilities(PartAbility.INPUT_ENERGY).setPreviewCount(2))
                            .or(abilities(PartAbility.MAINTENANCE).setPreviewCount(1)))
                    .build())
            .model(createWorkableCasingMachineModel(
                    GTCEu.id("block/casings/solid/machine_casing_inert_ptfe"),
                    GTCEu.id("block/multiblock/large_chemical_reactor"))
                    .andThen(model->model.addDynamicRenderer(XeroDynamicRendererHelpers::getTestRender)))
            .register();
    public static void init() {
    }
}

