package com.nekomu.xerocore.common.machine.multiblock.electric;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.data.chemical.ChemicalHelper;
import com.gregtechceu.gtceu.api.data.tag.TagPrefix;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.common.data.GTRecipeTypes;
import com.nekomu.xerocore.client.renderer.machine.XeroDynamicRendererHelpers;
import com.nekomu.xerocore.common.data.XeroBlocks;
import com.nekomu.xerocore.common.data.materials.XeroMaterials;

import static com.gregtechceu.gtceu.api.pattern.Predicates.abilities;
import static com.gregtechceu.gtceu.api.pattern.Predicates.blocks;
import static com.gregtechceu.gtceu.common.data.GTBlocks.CASING_BRONZE_BRICKS;
import static com.gregtechceu.gtceu.common.data.GTRecipeModifiers.BATCH_MODE;
import static com.gregtechceu.gtceu.common.data.GTRecipeModifiers.OC_NON_PERFECT_SUBTICK;
import static com.gregtechceu.gtceu.common.data.models.GTMachineModels.createWorkableCasingMachineModel;
import static com.nekomu.xerocore.api.registries.XeroRegistries.REGISTRATE;

public class testmachine {


    public static final MultiblockMachineDefinition TEST_MACHINE = REGISTRATE.multiblock("test_machine", WorkableElectricMultiblockMachine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .allowExtendedFacing(false)
            .recipeType(GTRecipeTypes.ALLOY_SMELTER_RECIPES)
            .recipeModifiers(OC_NON_PERFECT_SUBTICK, BATCH_MODE)
            .appearanceBlock(CASING_BRONZE_BRICKS)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("                                                                                                   ","                                          AAAAAAAAAAAAAAA                                          ","                                                                                                   ","                                          AAAAAAAAAAAAAAA                                          ","                                                                                                   ")
                    .aisle("                                          BBBBBBBBBBBBBBB                                          ","                                     AAAAACCCCCCCCCCCCCCCAAAAA                                     ","                                          CCCCCCCCCCCCCCC                                          ","                                     AAAAACCCCCCCCCCCCCCCAAAAA                                     ","                                          BBBBBBBBBBBBBBB                                          ")
                    .aisle("                                     BBBBBDDDDDDDDDDDDDDDBBBBB                                     ","                                  AAACCCCC               CCCCCAAA                                  ","                                     CCCCC               CCCCC                                     ","                                  AAACCCCC               CCCCCAAA                                  ","                                     BBBBBDDDDDDDDDDDDDDDBBBBB                                     ")
                    .aisle("                                  BBBDDDDDDDDDDDDDDDDDDDDDDDDDBBB                                  ","                                AACCC                         CCCAA                                ","                                  CCC                         CCC                                  ","                                AACCC                         CCCAA                                ","                                  BBBDDDDDDDDDDDDDDDDDDDDDDDDDBBB                                  ")
                    .aisle("                                BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                                ","                              AACC                               CCAA                              ","                                CC                               CC                                ","                              AACC                               CCAA                              ","                                BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                                ")
                    .aisle("                              BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                              ","                            AACC                                   CCAA                            ","                              CC                                   CC                              ","                            AACC                                   CCAA                            ","                              BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                              ")
                    .aisle("                            BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                            ","                          AACC                                       CCAA                          ","                            CC                                       CC                            ","                          AACC                                       CCAA                          ","                            BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                            ")
                    .aisle("                          BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                          ","                        AACC                                           CCAA                        ","                          CC                                           CC                          ","                        AACC                                           CCAA                        ","                          BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                          ")
                    .aisle("                        BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                        ","                       ACC                                               CCA                       ","                        CC                                               CC                        ","                       ACC                                               CCA                       ","                        BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                        ")
                    .aisle("                       BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                       ","                     AAC                                                   CAA                     ","                       C                                                   C                       ","                     AAC                                                   CAA                     ","                       BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                       ")
                    .aisle("                     BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                     ","                    ACC                                                     CCA                    ","                     CC                                                     CC                     ","                    ACC                                                     CCA                    ","                     BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                     ")
                    .aisle("                    BDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDB                    ","                   AC                      CCCCCCCCCCCCC                      CA                   ","                    C                      CCCCCCCCCCCCC                      C                    ","                   AC                      CCCCCCCCCCCCC                      CA                   ","                    BDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDB                    ")
                    .aisle("                   BDDDDDDDDDDDDDDDDDDBBBBB             BBBBBDDDDDDDDDDDDDDDDDDB                   ","                  AC                  CCCCCAAAAAAAAAAAAACCCCC                  CA                  ","                   C                  CCCCC             CCCCC                  C                   ","                  AC                  CCCCCAAAAAAAAAAAAACCCCC                  CA                  ","                   BDDDDDDDDDDDDDDDDDDBBBBB             BBBBBDDDDDDDDDDDDDDDDDDB                   ")
                    .aisle("                  BDDDDDDDDDDDDDDDDBBB                       BBBDDDDDDDDDDDDDDDDB                  ","                 AC                CCCAAAAA             AAAAACCC                CA                 ","                  C                CCC                       CCC                C                  ","                 AC                CCCAAAAA             AAAAACCC                CA                 ","                  BDDDDDDDDDDDDDDDDBBB                       BBBDDDDDDDDDDDDDDDDB                  ")
                    .aisle("                 BDDDDDDDDDDDDDDDBB                             BBDDDDDDDDDDDDDDDB                 ","                AC               CCAAA                       AAACC               CA                ","                 C               CC                             CC               C                 ","                AC               CCAAA                       AAACC               CA                ","                 BDDDDDDDDDDDDDDDBB                             BBDDDDDDDDDDDDDDDB                 ")
                    .aisle("                BDDDDDDDDDDDDDDBB                                 BBDDDDDDDDDDDDDDB                ","               AC              CCAA                             AACC              CA               ","                C              CC                                 CC              C                ","               AC              CCAA                             AACC              CA               ","                BDDDDDDDDDDDDDDBB                                 BBDDDDDDDDDDDDDDB                ")
                    .aisle("               BDDDDDDDDDDDDDDB                                     BDDDDDDDDDDDDDDB               ","              AC              CAA                                 AAC              CA              ","               C              C                                     C              C               ","              AC              CAA                                 AAC              CA              ","               BDDDDDDDDDDDDDDB                                     BDDDDDDDDDDDDDDB               ")
                    .aisle("              BDDDDDDDDDDDDDBB                                       BBDDDDDDDDDDDDDB              ","             AC             CCA                                     ACC             CA             ","              C             CC                                       CC             C              ","             AC             CCA                                     ACC             CA             ","              BDDDDDDDDDDDDDBB                                       BBDDDDDDDDDDDDDB              ")
                    .aisle("             BDDDDDDDDDDDDBB                                           BBDDDDDDDDDDDDB             ","            AC            CCAA                                       AACC            CA            ","             C            CC                                           CC            C             ","            AC            CCAA                                       AACC            CA            ","             BDDDDDDDDDDDDBB                                           BBDDDDDDDDDDDDB             ")
                    .aisle("            BDDDDDDDDDDDDB                                               BDDDDDDDDDDDDB            ","           AC            CAA                                           AAC            CA           ","            C            C                                               C            C            ","           AC            CAA                                           AAC            CA           ","            BDDDDDDDDDDDDB                                               BDDDDDDDDDDDDB            ")
                    .aisle("           BDDDDDDDDDDDDB                                                 BDDDDDDDDDDDDB           ","          AC            CA                                               AC            CA          ","           C            C                                                 C            C           ","          AC            CA                                               AC            CA          ","           BDDDDDDDDDDDDB                                                 BDDDDDDDDDDDDB           ")
                    .aisle("          BDDDDDDDDDDDDB                                                   BDDDDDDDDDDDDB          ","         AC            CA                                                 AC            CA         ","          C            C                                                   C            C          ","         AC            CA                                                 AC            CA         ","          BDDDDDDDDDDDDB                                                   BDDDDDDDDDDDDB          ")
                    .aisle("          BDDDDDDDDDDDB                                                     BDDDDDDDDDDDB          ","         AC           CA                                                   AC           CA         ","          C           C                                                     C           C          ","         AC           CA                                                   AC           CA         ","          BDDDDDDDDDDDB                                                     BDDDDDDDDDDDB          ")
                    .aisle("         BDDDDDDDDDDDB                                                       BDDDDDDDDDDDB         ","        AC           CA                                                     AC           CA        ","         C           C                                                       C           C         ","        AC           CA                                                     AC           CA        ","         BDDDDDDDDDDDB                                                       BDDDDDDDDDDDB         ")
                    .aisle("        BDDDDDDDDDDDB                                                         BDDDDDDDDDDDB        ","       AC           CA                                                       AC           CA       ","        C           C                      AAAAAAAAAAAAA                      C           C        ","       AC           CA                                                       AC           CA       ","        BDDDDDDDDDDDB                                                         BDDDDDDDDDDDB        ")
                    .aisle("        BDDDDDDDDDDB                                                           BDDDDDDDDDDB        ","       AC          CA                      BBBBBBBBBBBBB                      AC          CA       ","        C          C                    AAACCCCCCCCCCCCCAAA                    C          C        ","       AC          CA                      BBBBBBBBBBBBB                      AC          CA       ","        BDDDDDDDDDDB                                                           BDDDDDDDDDDB        ")
                    .aisle("       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ","      AC          CA                    BBBDDDDDDDDDDDDDBBB                    AC          CA      ","       C          C                   AACCC             CCCAA                   C          C       ","      AC          CA                    BBBDDDDDDDDDDDDDBBB                    AC          CA      ","       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ")
                    .aisle("       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ","      AC          CA                  BBDDDDDDDDDDDDDDDDDDDBB                  AC          CA      ","       C          C                 AACC                   CCAA                 C          C       ","      AC          CA                  BBDDDDDDDDDDDDDDDDDDDBB                  AC          CA      ","       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ")
                    .aisle("      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ","     AC          CA                 BBDDDDDDDDDDDDDDDDDDDDDDDBB                 AC          CA     ","      C          C                 ACC                       CCA                 C          C      ","     AC          CA                 BBDDDDDDDDDDDDDDDDDDDDDDDBB                 AC          CA     ","      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ")
                    .aisle("      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ","     AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA     ","      C          C                AC                           CA                C          C      ","     AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA     ","      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ")
                    .aisle("     BDDDDDDDDDDB                                                                 BDDDDDDDDDDB     ","    AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA    ","     C          C                AC                             CA                C          C     ","    AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA    ","     BDDDDDDDDDDB                                                                 BDDDDDDDDDDB     ")
                    .aisle("     BDDDDDDDDDB                                                                   BDDDDDDDDDB     ","    AC         CA                BDDDDDDDDDDDBBBBBBBBBDDDDDDDDDDDB                AC         CA    ","     C         C                AC           CCCCCCCCC           CA                C         C     ","    AC         CA                BDDDDDDDDDDDBBBBBBBBBDDDDDDDDDDDB                AC         CA    ","     BDDDDDDDDDB                                                                   BDDDDDDDDDB     ")
                    .aisle("    BDDDDDDDDDDB                                                                   BDDDDDDDDDDB    ","   AC          CA               BDDDDDDDDDBBB         BBBDDDDDDDDDB               AC          CA   ","    C          C               AC         CCCAAAAAAAAACCC         CA               C          C    ","   AC          CA               BDDDDDDDDDBBB         BBBDDDDDDDDDB               AC          CA   ","    BDDDDDDDDDDB                                                                   BDDDDDDDDDDB    ")
                    .aisle("    BDDDDDDDDDB                                                                     BDDDDDDDDDB    ","   AC         CA               BDDDDDDDDBB               BBDDDDDDDDB               AC         CA   ","    C         C               AC        CCAAA         AAACC        CA               C         C    ","   AC         CA               BDDDDDDDDBB               BBDDDDDDDDB               AC         CA   ","    BDDDDDDDDDB                                                                     BDDDDDDDDDB    ")
                    .aisle("   BDDDDDDDDDDB                                                                     BDDDDDDDDDDB   ","  AC          CA              BDDDDDDDBB                   BBDDDDDDDB              AC          CA  ","   C          C              AC       CCAA               AACC       CA              C          C   ","  AC          CA              BDDDDDDDBB                   BBDDDDDDDB              AC          CA  ","   BDDDDDDDDDDB                                                                     BDDDDDDDDDDB   ")
                    .aisle("   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ","  AC         CA              BDDDDDDDB                       BDDDDDDDB              AC         CA  ","   C         C              AC       CAA                   AAC       CA              C         C   ","  AC         CA              BDDDDDDDB                       BDDDDDDDB              AC         CA  ","   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ")
                    .aisle("   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ","  AC         CA             BDDDDDDDB                         BDDDDDDDB             AC         CA  ","   C         C             AC       CA                       AC       CA             C         C   ","  AC         CA             BDDDDDDDB                         BDDDDDDDB             AC         CA  ","   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ")
                    .aisle("  BDDDDDDDDDDB                                                                       BDDDDDDDDDDB  "," AC          CA             BDDDDDDB                           BDDDDDDB             AC          CA ","  C          C             AC      CA                         AC      CA             C          C  "," AC          CA             BDDDDDDB                           BDDDDDDB             AC          CA ","  BDDDDDDDDDDB                                                                       BDDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  C         C             AC      CA                           AC      CA             C         C  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  C         C             AC      CA                           AC      CA             C         C  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  C         C            AC      CA                             AC      CA            C         C  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  C         C            AC      CA                             AC      CA            C         C  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle(" BDDDDDDDDDDB                                                                         BDDDDDDDDDDB ","AC          CA            BDDDDDB                                 BDDDDDB            AC          CA"," C          C            AC     CA                               AC     CA            C          C ","AC          CA            BDDDDDB                                 BDDDDDB            AC          CA"," BDDDDDDDDDDB                                                                         BDDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," C         C            AC      CA                               AC      CA            C         C ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," C         C            AC      CA                               AC      CA            C         C ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," C         C            AC     CA                                 AC     CA            C         C ","AC         CA            BDDDDDB                                   BDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," C         C            AC      CA                               AC      CA            C         C ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDB                                                                           BDDDDDDDDDB ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," C         C            AC      CA                               AC      CA            C         C ","AC         CA            BDDDDDDB                                 BDDDDDDB            AC         CA"," BDDDDDDDDDB                                                                           BDDDDDDDDDB ")
                    .aisle(" BDDDDDDDDDDB                                                                         BDDDDDDDDDDB ","AC          CA            BDDDDDB                                 BDDDDDB            AC          CA"," C          C            AC     CA                               AC     CA            C          C ","AC          CA            BDDDDDB                                 BDDDDDB            AC          CA"," BDDDDDDDDDDB                                                                         BDDDDDDDDDDB ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  C         C            AC      CA                             AC      CA            C         C  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  C         C            AC      CA                             AC      CA            C         C  "," AC         CA            BDDDDDDB                               BDDDDDDB            AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  C         C             AC      CA                           AC      CA             C         C  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDB                                                                         BDDDDDDDDDB  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  C         C             AC      CA                           AC      CA             C         C  "," AC         CA             BDDDDDDB                             BDDDDDDB             AC         CA ","  BDDDDDDDDDB                                                                         BDDDDDDDDDB  ")
                    .aisle("  BDDDDDDDDDDB                                                                       BDDDDDDDDDDB  "," AC          CA             BDDDDDDB                           BDDDDDDB             AC          CA ","  C          C             AC      CA                         AC      CA             C          C  "," AC          CA             BDDDDDDB                           BDDDDDDB             AC          CA ","  BDDDDDDDDDDB                                                                       BDDDDDDDDDDB  ")
                    .aisle("   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ","  AC         CA             BDDDDDDDB                         BDDDDDDDB             AC         CA  ","   C         C             AC       CA                       AC       CA             C         C   ","  AC         CA             BDDDDDDDB                         BDDDDDDDB             AC         CA  ","   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ")
                    .aisle("   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ","  AC         CA              BDDDDDDDB                       BDDDDDDDB              AC         CA  ","   C         C              AC       CAA                   AAC       CA              C         C   ","  AC         CA              BDDDDDDDB                       BDDDDDDDB              AC         CA  ","   BDDDDDDDDDB                                                                       BDDDDDDDDDB   ")
                    .aisle("   BDDDDDDDDDDB                                                                     BDDDDDDDDDDB   ","  AC          CA              BDDDDDDDBB                   BBDDDDDDDB              AC          CA  ","   C          C              AC       CCAA               AACC       CA              C          C   ","  AC          CA              BDDDDDDDBB                   BBDDDDDDDB              AC          CA  ","   BDDDDDDDDDDB                                                                     BDDDDDDDDDDB   ")
                    .aisle("    BDDDDDDDDDB                                                                     BDDDDDDDDDB    ","   AC         CA               BDDDDDDDDBB               BBDDDDDDDDB               AC         CA   ","    C         C               AC        CCAAA         AAACC        CA               C         C    ","   AC         CA               BDDDDDDDDBB               BBDDDDDDDDB               AC         CA   ","    BDDDDDDDDDB                                                                     BDDDDDDDDDB    ")
                    .aisle("    BDDDDDDDDDDB                                                                   BDDDDDDDDDDB    ","   AC          CA               BDDDDDDDDDBBB         BBBDDDDDDDDDB               AC          CA   ","    C          C               AC         CCCAAAAAAAAACCC         CA               C          C    ","   AC          CA               BDDDDDDDDDBBB         BBBDDDDDDDDDB               AC          CA   ","    BDDDDDDDDDDB                                                                   BDDDDDDDDDDB    ")
                    .aisle("     BDDDDDDDDDB                                                                   BDDDDDDDDDB     ","    AC         CA                BDDDDDDDDDDDBBBBBBBBBDDDDDDDDDDDB                AC         CA    ","     C         C                AC           CCCCCCCCC           CA                C         C     ","    AC         CA                BDDDDDDDDDDDBBBBBBBBBDDDDDDDDDDDB                AC         CA    ","     BDDDDDDDDDB                                                                   BDDDDDDDDDB     ")
                    .aisle("     BDDDDDDDDDDB                                                                 BDDDDDDDDDDB     ","    AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA    ","     C          C                AC                             CA                C          C     ","    AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA    ","     BDDDDDDDDDDB                                                                 BDDDDDDDDDDB     ")
                    .aisle("      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ","     AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA     ","      C          C                AC                           CA                C          C      ","     AC          CA                BDDDDDDDDDDDDDDDDDDDDDDDDDDDB                AC          CA     ","      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ")
                    .aisle("      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ","     AC          CA                 BBDDDDDDDDDDDDDDDDDDDDDDDBB                 AC          CA     ","      C          C                 ACC                       CCA                 C          C      ","     AC          CA                 BBDDDDDDDDDDDDDDDDDDDDDDDBB                 AC          CA     ","      BDDDDDDDDDDB                                                               BDDDDDDDDDDB      ")
                    .aisle("       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ","      AC          CA                  BBDDDDDDDDDDDDDDDDDDDBB                  AC          CA      ","       C          C                 AACC                   CCAA                 C          C       ","      AC          CA                  BBDDDDDDDDDDDDDDDDDDDBB                  AC          CA      ","       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ")
                    .aisle("       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ","      AC          CA                    BBBDDDDDDDDDDDDDBBB                    AC          CA      ","       C          C                   AACCC             CCCAA                   C          C       ","      AC          CA                    BBBDDDDDDDDDDDDDBBB                    AC          CA      ","       BDDDDDDDDDDB                                                             BDDDDDDDDDDB       ")
                    .aisle("        BDDDDDDDDDDB                                                           BDDDDDDDDDDB        ","       AC          CA                      BBBBBBBBBBBBB                      AC          CA       ","        C          C                    AAACCCCCCCCCCCCCAAA                    C          C        ","       AC          CA                      BBBBBBBBBBBBB                      AC          CA       ","        BDDDDDDDDDDB                                                           BDDDDDDDDDDB        ")
                    .aisle("        BDDDDDDDDDDDB                                                         BDDDDDDDDDDDB        ","       AC           CA                                                       AC           CA       ","        C           C                      AAAAAAAAAAAAA                      C           C        ","       AC           CA                                                       AC           CA       ","        BDDDDDDDDDDDB                                                         BDDDDDDDDDDDB        ")
                    .aisle("         BDDDDDDDDDDDB                                                       BDDDDDDDDDDDB         ","        AC           CA                                                     AC           CA        ","         C           C                                                       C           C         ","        AC           CA                                                     AC           CA        ","         BDDDDDDDDDDDB                                                       BDDDDDDDDDDDB         ")
                    .aisle("          BDDDDDDDDDDDB                                                     BDDDDDDDDDDDB          ","         AC           CA                                                   AC           CA         ","          C           C                                                     C           C          ","         AC           CA                                                   AC           CA         ","          BDDDDDDDDDDDB                                                     BDDDDDDDDDDDB          ")
                    .aisle("          BDDDDDDDDDDDDB                                                   BDDDDDDDDDDDDB          ","         AC            CA                                                 AC            CA         ","          C            C                                                   C            C          ","         AC            CA                                                 AC            CA         ","          BDDDDDDDDDDDDB                                                   BDDDDDDDDDDDDB          ")
                    .aisle("           BDDDDDDDDDDDDB                                                 BDDDDDDDDDDDDB           ","          AC            CA                                               AC            CA          ","           C            C                                                 C            C           ","          AC            CA                                               AC            CA          ","           BDDDDDDDDDDDDB                                                 BDDDDDDDDDDDDB           ")
                    .aisle("            BDDDDDDDDDDDDB                                               BDDDDDDDDDDDDB            ","           AC            CAA                                           AAC            CA           ","            C            C                                               C            C            ","           AC            CAA                                           AAC            CA           ","            BDDDDDDDDDDDDB                                               BDDDDDDDDDDDDB            ")
                    .aisle("             BDDDDDDDDDDDDBB                                           BBDDDDDDDDDDDDB             ","            AC            CCAA                                       AACC            CA            ","             C            CC                                           CC            C             ","            AC            CCAA                                       AACC            CA            ","             BDDDDDDDDDDDDBB                                           BBDDDDDDDDDDDDB             ")
                    .aisle("              BDDDDDDDDDDDDDBB                                       BBDDDDDDDDDDDDDB              ","             AC             CCA                                     ACC             CA             ","              C             CC                                       CC             C              ","             AC             CCA                                     ACC             CA             ","              BDDDDDDDDDDDDDBB                                       BBDDDDDDDDDDDDDB              ")
                    .aisle("               BDDDDDDDDDDDDDDB                                     BDDDDDDDDDDDDDDB               ","              AC              CAA                                 AAC              CA              ","               C              C                                     C              C               ","              AC              CAA                                 AAC              CA              ","               BDDDDDDDDDDDDDDB                                     BDDDDDDDDDDDDDDB               ")
                    .aisle("                BDDDDDDDDDDDDDDBB                                 BBDDDDDDDDDDDDDDB                ","               AC              CCAA                             AACC              CA               ","                C              CC                                 CC              C                ","               AC              CCAA                             AACC              CA               ","                BDDDDDDDDDDDDDDBB                                 BBDDDDDDDDDDDDDDB                ")
                    .aisle("                 BDDDDDDDDDDDDDDDBB                             BBDDDDDDDDDDDDDDDB                 ","                AC               CCAAA                       AAACC               CA                ","                 C               CC                             CC               C                 ","                AC               CCAAA                       AAACC               CA                ","                 BDDDDDDDDDDDDDDDBB                             BBDDDDDDDDDDDDDDDB                 ")
                    .aisle("                  BDDDDDDDDDDDDDDDDBBB                       BBBDDDDDDDDDDDDDDDDB                  ","                 AC                CCCAAAAA             AAAAACCC                CA                 ","                  C                CCC                       CCC                C                  ","                 AC                CCCAAAAA             AAAAACCC                CA                 ","                  BDDDDDDDDDDDDDDDDBBB                       BBBDDDDDDDDDDDDDDDDB                  ")
                    .aisle("                   BDDDDDDDDDDDDDDDDDDBBBBB             BBBBBDDDDDDDDDDDDDDDDDDB                   ","                  AC                  CCCCCAAAAAAAAAAAAACCCCC                  CA                  ","                   C                  CCCCC             CCCCC                  C                   ","                  AC                  CCCCCAAAAAAAAAAAAACCCCC                  CA                  ","                   BDDDDDDDDDDDDDDDDDDBBBBB             BBBBBDDDDDDDDDDDDDDDDDDB                   ")
                    .aisle("                    BDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDB                    ","                   AC                      CCCCCCCCCCCCC                      CA                   ","                    C                      CCCCCCCCCCCCC                      C                    ","                   AC                      CCCCCCCCCCCCC                      CA                   ","                    BDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDDDDDDDDDB                    ")
                    .aisle("                     BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                     ","                    ACC                                                     CCA                    ","                     CC                                                     CC                     ","                    ACC                                                     CCA                    ","                     BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                     ")
                    .aisle("                       BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                       ","                     AAC                                                   CAA                     ","                       C                                                   C                       ","                     AAC                                                   CAA                     ","                       BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB                       ")
                    .aisle("                        BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                        ","                       ACC                                               CCA                       ","                        CC                                               CC                        ","                       ACC                                               CCA                       ","                        BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                        ")
                    .aisle("                          BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                          ","                        AACC                                           CCAA                        ","                          CC                                           CC                          ","                        AACC                                           CCAA                        ","                          BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                          ")
                    .aisle("                            BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                            ","                          AACC                                       CCAA                          ","                            CC                                       CC                            ","                          AACC                                       CCAA                          ","                            BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                            ")
                    .aisle("                              BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                              ","                            AACC                                   CCAA                            ","                              CC                                   CC                              ","                            AACC                                   CCAA                            ","                              BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                              ")
                    .aisle("                                BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                                ","                              AACC                               CCAA                              ","                                CC                               CC                                ","                              AACC                               CCAA                              ","                                BBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBB                                ")
                    .aisle("                                  BBBDDDDDDDDDDDDDDDDDDDDDDDDDBBB                                  ","                                AACCC                         CCCAA                                ","                                  CCC                         CCC                                  ","                                AACCC                         CCCAA                                ","                                  BBBDDDDDDDDDDDDDDDDDDDDDDDDDBBB                                  ")
                    .aisle("                                     BBBBBDDDDDDDDDDDDDDDBBBBB                                     ","                                  AAACCCCC               CCCCCAAA                                  ","                                     CCCCC               CCCCC                                     ","                                  AAACCCCC               CCCCCAAA                                  ","                                     BBBBBDDDDDDDDDDDDDDDBBBBB                                     ")
                    .aisle("                                          BBBBBBBBBBBBBBB                                          ","                                     AAAAACCCCCCCCCCCCCCCAAAAA                                     ","                                          CCCCCCC@CCCCCCC                                          ","                                     AAAAACCCCCCCCCCCCCCCAAAAA                                     ","                                          BBBBBBBBBBBBBBB                                          ")
                    .aisle("                                                                                                   ","                                          AAAAAAAAAAAAAAA                                          ","                                                                                                   ","                                          AAAAAAAAAAAAAAA                                          ","                                                                                                   ")
                    .where('@', Predicates.controller(blocks(definition.getBlock())))
                    .where(' ', Predicates.any())
                    .where('A', blocks(ChemicalHelper.getBlock(TagPrefix.frameGt, XeroMaterials.TestMaterial)))
                    .where('C', blocks(XeroBlocks.TESTONE_CASING.get()))
                    .where('D', blocks(XeroBlocks.TESTTWO_CASING.get()))
                    .where('B', blocks(XeroBlocks.TESTTHREE_CASING.get())
                            .or(abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
                            .or(abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                            .or(abilities(PartAbility.INPUT_ENERGY).setPreviewCount(2))
                            .or(abilities(PartAbility.MAINTENANCE).setPreviewCount(1)))
                    .build())
            .model(createWorkableCasingMachineModel(
                    GTCEu.id("block/casings/solid/machine_casing_inert_ptfe"),
                    GTCEu.id("block/multiblock/large_chemical_reactor"))
                    .andThen(model->model.addDynamicRenderer(XeroDynamicRendererHelpers::getTestRender)))
            .register();
    public static void init() {
    }
}

